name: Sync releases with main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-release-branches:
    strategy:
      matrix:
        version: ["24.05"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: "release-${{ matrix.version }}"
        fetch-depth: 0
    - run: |
        git config --global merge.ours.driver true
        git config --global user.name 'autofirma-nix-bot'
        git config --global user.email 'autofirma-nix-bot@users.noreply.github.com'
        git config --global pull.rebase false
    - run: git merge --no-ff origin/main
    - run: git push


